# Generated by Django 4.2.16 on 2024-10-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='workersneeded',
            field=models.IntegerField(default=0),
        ),
    ]
