# Generated by Django 4.2.16 on 2024-10-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_projectpost_workersneeded'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
